# .gitlab-ci.yml
stages:
  - build
  - test
  - package

variables:
  # Define the Gradle user home directory
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  # Ensure Gradle wrapper is executable
  - chmod +x ./gradlew

build:
  stage: build
  image: gradle:jdk23-alpine  # Use appropriate Gradle and JDK version
  script:
    - ./gradlew clean assemble
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - master
    - develop
    - feature/*

test:
  stage: test
  image: gradle:jdk23-alpine
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - build/test-results/test/
      - build/reports/tests/test/
  only:
    - master
    - develop
    - feature/*

package:
  stage: package
  image: gradle:jdk23-alpine
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - master
