spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL:http://localhost:8090/realms/The-Homeric-Odyssey-Vendor}
          jwk-set-uri: ${KEYCLOAK_BASE_JWK:http://localhost:8090/realms/The-Homeric-Odyssey-Vendor/protocol/openid-connect/certs}
  application.name: core-app
  datasource:
    password: ${DATASOURCE_PASSWORD:example}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/core-app}
    username: ${DATASOURCE_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.yaml

registry:
  api:
    url: ${APPLICATION_REGISTRY_URL:http://localhost:8080}

logging:
  level:
    root: info

resource-server:
  client-id: ${KEYCLOAK_CLIENT_ID:auth-server-client}

event-log:
  api:
    url: ${EVENT_LOG_URL:http://127.0.0.1:8088}

core-app:
  application:
    - product-publicly-available: ${CORE_PRODUCT_PUBLICLY_AVAILABLE_STATUES:AVAILABLE, PREORDER, EMPTY}

security:
  authentication:
    url: ${AUTH_SERVER_URL:http://localhost/auth/realms/The-Homeric-Odyssey-Vendor/protocol/openid-connect/token}
    client-id: ${KEYCLOAK_CLIENT_ID:auth-server-client}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:Y9zA2dnuBLrenro4uKEGQQRyjCDPUwAX}
    system-user:
      username: ${SYSTEM_USERNAME:admin}
      password: ${SYSTEM_PASSWORD:admin123}